{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "c57f5a68",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting streamlit\n",
      "  Downloading streamlit-1.46.1-py3-none-any.whl.metadata (9.0 kB)\n",
      "Collecting altair<6,>=4.0 (from streamlit)\n",
      "  Downloading altair-5.5.0-py3-none-any.whl.metadata (11 kB)\n",
      "Collecting blinker<2,>=1.5.0 (from streamlit)\n",
      "  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)\n",
      "Collecting cachetools<7,>=4.0 (from streamlit)\n",
      "  Downloading cachetools-6.1.0-py3-none-any.whl.metadata (5.4 kB)\n",
      "Collecting click<9,>=7.0 (from streamlit)\n",
      "  Downloading click-8.2.1-py3-none-any.whl.metadata (2.5 kB)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from streamlit) (2.3.1)\n",
      "Requirement already satisfied: packaging<26,>=20 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from streamlit) (25.0)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from streamlit) (2.3.0)\n",
      "Requirement already satisfied: pillow<12,>=7.1.0 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from streamlit) (11.2.1)\n",
      "Collecting protobuf<7,>=3.20 (from streamlit)\n",
      "  Downloading protobuf-6.31.1-cp310-abi3-win_amd64.whl.metadata (593 bytes)\n",
      "Collecting pyarrow>=7.0 (from streamlit)\n",
      "  Downloading pyarrow-20.0.0-cp313-cp313-win_amd64.whl.metadata (3.4 kB)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from streamlit) (2.32.4)\n",
      "Collecting tenacity<10,>=8.1.0 (from streamlit)\n",
      "  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting toml<2,>=0.10.1 (from streamlit)\n",
      "  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)\n",
      "Collecting typing-extensions<5,>=4.4.0 (from streamlit)\n",
      "  Using cached typing_extensions-4.14.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "Collecting watchdog<7,>=2.1.5 (from streamlit)\n",
      "  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)\n",
      "Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)\n",
      "  Downloading GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)\n",
      "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
      "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Collecting jinja2 (from altair<6,>=4.0->streamlit)\n",
      "  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)\n",
      "Collecting jsonschema>=3.0 (from altair<6,>=4.0->streamlit)\n",
      "  Using cached jsonschema-4.24.0-py3-none-any.whl.metadata (7.8 kB)\n",
      "Collecting narwhals>=1.14.2 (from altair<6,>=4.0->streamlit)\n",
      "  Downloading narwhals-1.44.0-py3-none-any.whl.metadata (11 kB)\n",
      "Requirement already satisfied: colorama in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)\n",
      "Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)\n",
      "  Downloading smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4.2)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.10)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2025.6.15)\n",
      "Collecting MarkupSafe>=2.0 (from jinja2->altair<6,>=4.0->streamlit)\n",
      "  Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl.metadata (4.1 kB)\n",
      "Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Using cached attrs-25.3.0-py3-none-any.whl.metadata (10 kB)\n",
      "Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Using cached jsonschema_specifications-2025.4.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Using cached referencing-0.36.2-py3-none-any.whl.metadata (2.8 kB)\n",
      "Collecting rpds-py>=0.7.1 (from jsonschema>=3.0->altair<6,>=4.0->streamlit)\n",
      "  Using cached rpds_py-0.25.1-cp313-cp313-win_amd64.whl.metadata (4.2 kB)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\acer\\onedrive\\documents\\spotify mood timeline\\.venv\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Downloading streamlit-1.46.1-py3-none-any.whl (10.1 MB)\n",
      "   ---------------------------------------- 0.0/10.1 MB ? eta -:--:--\n",
      "   ------ --------------------------------- 1.6/10.1 MB 10.4 MB/s eta 0:00:01\n",
      "   ------- -------------------------------- 1.8/10.1 MB 5.0 MB/s eta 0:00:02\n",
      "   ------------ --------------------------- 3.1/10.1 MB 4.9 MB/s eta 0:00:02\n",
      "   ------------------ --------------------- 4.7/10.1 MB 5.9 MB/s eta 0:00:01\n",
      "   ----------------------- ---------------- 6.0/10.1 MB 5.8 MB/s eta 0:00:01\n",
      "   ---------------------------- ----------- 7.1/10.1 MB 5.8 MB/s eta 0:00:01\n",
      "   -------------------------------- ------- 8.1/10.1 MB 5.7 MB/s eta 0:00:01\n",
      "   ----------------------------------- ---- 8.9/10.1 MB 5.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------  10.0/10.1 MB 5.4 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 10.1/10.1 MB 5.1 MB/s eta 0:00:00\n",
      "Downloading altair-5.5.0-py3-none-any.whl (731 kB)\n",
      "   ---------------------------------------- 0.0/731.2 kB ? eta -:--:--\n",
      "   ---------------------------------------- 731.2/731.2 kB 3.4 MB/s eta 0:00:00\n",
      "Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)\n",
      "Downloading cachetools-6.1.0-py3-none-any.whl (11 kB)\n",
      "Downloading click-8.2.1-py3-none-any.whl (102 kB)\n",
      "Downloading GitPython-3.1.44-py3-none-any.whl (207 kB)\n",
      "Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)\n",
      "Downloading protobuf-6.31.1-cp310-abi3-win_amd64.whl (435 kB)\n",
      "Downloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
      "   ---------------------------------------- 0.0/6.9 MB ? eta -:--:--\n",
      "   ---- ----------------------------------- 0.8/6.9 MB 4.8 MB/s eta 0:00:02\n",
      "   ---------- ----------------------------- 1.8/6.9 MB 4.7 MB/s eta 0:00:02\n",
      "   ---------------- ----------------------- 2.9/6.9 MB 4.8 MB/s eta 0:00:01\n",
      "   --------------------- ------------------ 3.7/6.9 MB 4.5 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 4.7/6.9 MB 4.5 MB/s eta 0:00:01\n",
      "   --------------------------------- ------ 5.8/6.9 MB 4.6 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 6.3/6.9 MB 4.5 MB/s eta 0:00:01\n",
      "   ---------------------------------------  6.8/6.9 MB 4.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 6.9/6.9 MB 4.0 MB/s eta 0:00:00\n",
      "Downloading smmap-5.0.2-py3-none-any.whl (24 kB)\n",
      "Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)\n",
      "Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)\n",
      "Using cached typing_extensions-4.14.0-py3-none-any.whl (43 kB)\n",
      "Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)\n",
      "Using cached jinja2-3.1.6-py3-none-any.whl (134 kB)\n",
      "Using cached jsonschema-4.24.0-py3-none-any.whl (88 kB)\n",
      "Using cached attrs-25.3.0-py3-none-any.whl (63 kB)\n",
      "Using cached jsonschema_specifications-2025.4.1-py3-none-any.whl (18 kB)\n",
      "Using cached MarkupSafe-3.0.2-cp313-cp313-win_amd64.whl (15 kB)\n",
      "Downloading narwhals-1.44.0-py3-none-any.whl (365 kB)\n",
      "Downloading pyarrow-20.0.0-cp313-cp313-win_amd64.whl (25.7 MB)\n",
      "   ---------------------------------------- 0.0/25.7 MB ? eta -:--:--\n",
      "    --------------------------------------- 0.5/25.7 MB 3.0 MB/s eta 0:00:09\n",
      "   - -------------------------------------- 1.0/25.7 MB 2.7 MB/s eta 0:00:10\n",
      "   -- ------------------------------------- 1.6/25.7 MB 2.8 MB/s eta 0:00:09\n",
      "   --- ------------------------------------ 2.4/25.7 MB 2.9 MB/s eta 0:00:09\n",
      "   ---- ----------------------------------- 3.1/25.7 MB 3.0 MB/s eta 0:00:08\n",
      "   ----- ---------------------------------- 3.7/25.7 MB 3.1 MB/s eta 0:00:08\n",
      "   ------ --------------------------------- 4.5/25.7 MB 3.2 MB/s eta 0:00:07\n",
      "   -------- ------------------------------- 5.2/25.7 MB 3.3 MB/s eta 0:00:07\n",
      "   --------- ------------------------------ 6.3/25.7 MB 3.4 MB/s eta 0:00:06\n",
      "   ---------- ----------------------------- 6.8/25.7 MB 3.4 MB/s eta 0:00:06\n",
      "   ----------- ---------------------------- 7.6/25.7 MB 3.3 MB/s eta 0:00:06\n",
      "   ------------ --------------------------- 8.1/25.7 MB 3.3 MB/s eta 0:00:06\n",
      "   ------------- -------------------------- 8.9/25.7 MB 3.3 MB/s eta 0:00:06\n",
      "   -------------- ------------------------- 9.4/25.7 MB 3.3 MB/s eta 0:00:05\n",
      "   --------------- ------------------------ 10.2/25.7 MB 3.3 MB/s eta 0:00:05\n",
      "   ----------------- ---------------------- 11.0/25.7 MB 3.3 MB/s eta 0:00:05\n",
      "   ------------------ --------------------- 11.8/25.7 MB 3.4 MB/s eta 0:00:05\n",
      "   ------------------- -------------------- 12.3/25.7 MB 3.4 MB/s eta 0:00:04\n",
      "   -------------------- ------------------- 12.8/25.7 MB 3.3 MB/s eta 0:00:04\n",
      "   --------------------- ------------------ 13.6/25.7 MB 3.3 MB/s eta 0:00:04\n",
      "   ---------------------- ----------------- 14.2/25.7 MB 3.3 MB/s eta 0:00:04\n",
      "   ---------------------- ----------------- 14.7/25.7 MB 3.3 MB/s eta 0:00:04\n",
      "   ----------------------- ---------------- 15.2/25.7 MB 3.2 MB/s eta 0:00:04\n",
      "   ------------------------ --------------- 15.7/25.7 MB 3.2 MB/s eta 0:00:04\n",
      "   ------------------------- -------------- 16.3/25.7 MB 3.1 MB/s eta 0:00:04\n",
      "   ------------------------- -------------- 16.5/25.7 MB 3.1 MB/s eta 0:00:03\n",
      "   -------------------------- ------------- 17.0/25.7 MB 3.1 MB/s eta 0:00:03\n",
      "   --------------------------- ------------ 17.8/25.7 MB 3.1 MB/s eta 0:00:03\n",
      "   ---------------------------- ----------- 18.4/25.7 MB 3.1 MB/s eta 0:00:03\n",
      "   ----------------------------- ---------- 18.9/25.7 MB 3.0 MB/s eta 0:00:03\n",
      "   ------------------------------ --------- 19.7/25.7 MB 3.0 MB/s eta 0:00:02\n",
      "   ------------------------------- -------- 20.2/25.7 MB 3.0 MB/s eta 0:00:02\n",
      "   -------------------------------- ------- 21.0/25.7 MB 3.1 MB/s eta 0:00:02\n",
      "   --------------------------------- ------ 21.8/25.7 MB 3.1 MB/s eta 0:00:02\n",
      "   ----------------------------------- ---- 22.5/25.7 MB 3.1 MB/s eta 0:00:02\n",
      "   ----------------------------------- ---- 23.1/25.7 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 23.6/25.7 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------- -- 24.1/25.7 MB 3.1 MB/s eta 0:00:01\n",
      "   -------------------------------------- - 24.6/25.7 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------  25.4/25.7 MB 3.1 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 25.7/25.7 MB 3.0 MB/s eta 0:00:00\n",
      "Using cached referencing-0.36.2-py3-none-any.whl (26 kB)\n",
      "Using cached rpds_py-0.25.1-cp313-cp313-win_amd64.whl (234 kB)\n",
      "Installing collected packages: watchdog, typing-extensions, toml, tenacity, smmap, rpds-py, pyarrow, protobuf, narwhals, MarkupSafe, click, cachetools, blinker, attrs, referencing, jinja2, gitdb, pydeck, jsonschema-specifications, gitpython, jsonschema, altair, streamlit\n",
      "\n",
      "   - --------------------------------------  1/23 [typing-extensions]\n",
      "   ------ ---------------------------------  4/23 [smmap]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ---------- -----------------------------  6/23 [pyarrow]\n",
      "   ------------ ---------------------------  7/23 [protobuf]\n",
      "   ------------ ---------------------------  7/23 [protobuf]\n",
      "   ------------- --------------------------  8/23 [narwhals]\n",
      "   ------------- --------------------------  8/23 [narwhals]\n",
      "   ------------- --------------------------  8/23 [narwhals]\n",
      "   ------------- --------------------------  8/23 [narwhals]\n",
      "   ------------- --------------------------  8/23 [narwhals]\n",
      "   ----------------- ---------------------- 10/23 [click]\n",
      "   ---------------------- ----------------- 13/23 [attrs]\n",
      "   -------------------------- ------------- 15/23 [jinja2]\n",
      "   -------------------------- ------------- 15/23 [jinja2]\n",
      "   --------------------------- ------------ 16/23 [gitdb]\n",
      "   ----------------------------- ---------- 17/23 [pydeck]\n",
      "   ------------------------------- -------- 18/23 [jsonschema-specifications]\n",
      "   --------------------------------- ------ 19/23 [gitpython]\n",
      "   ---------------------------------- ----- 20/23 [jsonschema]\n",
      "   ------------------------------------ --- 21/23 [altair]\n",
      "   ------------------------------------ --- 21/23 [altair]\n",
      "   ------------------------------------ --- 21/23 [altair]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   -------------------------------------- - 22/23 [streamlit]\n",
      "   ---------------------------------------- 23/23 [streamlit]\n",
      "\n",
      "Successfully installed MarkupSafe-3.0.2 altair-5.5.0 attrs-25.3.0 blinker-1.9.0 cachetools-6.1.0 click-8.2.1 gitdb-4.0.12 gitpython-3.1.44 jinja2-3.1.6 jsonschema-4.24.0 jsonschema-specifications-2025.4.1 narwhals-1.44.0 protobuf-6.31.1 pyarrow-20.0.0 pydeck-0.9.1 referencing-0.36.2 rpds-py-0.25.1 smmap-5.0.2 streamlit-1.46.1 tenacity-9.1.2 toml-0.10.2 typing-extensions-4.14.0 watchdog-6.0.0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-06-27 20:02:32.239 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-27 20:02:32.406 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run c:\\Users\\ACER\\OneDrive\\Documents\\spotify mood timeline\\.venv\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-06-27 20:02:32.407 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-06-27 20:02:32.409 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "!pip install streamlit\n",
    "import streamlit as st\n",
    "st.title(\"Spotify Auth Placeholder\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
